###Mostar todos los usuarios
GET http://localhost:3000/users/

###Mostar usuario por ID
GET http://localhost:3000/users/1

//TAREA
### Agregar usuario
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "Regina",
  "password": "regi123",
  "email": "regina123@gmail.com"
}

### Actualizar usuario
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "Lady Sthefany",
  "password": "nueva123"
}

###Login usuario
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Lady Sthefany",
  "password": "nueva123"
}

###Elimimar usuario
DELETE http://localhost:3000/users/2


