GET http://localhost:3000/users/

###
GET http://localhost:3000/users/1

//TAREA
###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "Fany",
  "password": "hola123",
  "email": "fany@gmail.com"
}


###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "Lady"
}

###
DELETE http://localhost:3000/users/2