POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "lady@gmail.com",
    "password":"lady123"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzOTQwNTAyLCJleHAiOjE3MzM5NDA4MDJ9.ISad8k1WUA7vqw0oqRtbfr2eSXMkINX10Ru83XIqHkY
